version: 1.0.{build}
image: Visual Studio 2022
init:
- cmd: git submodule update --init
install:
- cmd: >-
    "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"

    nmake restore
build_script:
- cmd: >-
    nmake

    nmake deploy
artifacts:
- path: RecompressZip-net9.0.zip
  name: .NET 9 binary of $(SOLUTION_NAME)
- path: RecompressZip-net481.zip
  name: .NET Framework 4.8.1 binary of $(SOLUTION_NAME)
