SOLUTION_NAME = RecompressZip
SOLUTION_FILE = $(SOLUTION_NAME).sln
MAIN_PROJECT_FILE = $(SOLUTION_NAME)\$(SOLUTION_NAME).csproj
PROJECT_DIRS = $(SOLUTION_NAME) Koturn.CommandLine\Koturn.CommandLine Koturn.Zopfli\Koturn.Zopfli
CXX_PROJECT_DIRS = Koturn.Zopfli\libzopfli
ARTIFACTS_BASEDIR = Artifacts
ARTIFACTS_SUBDIR_BASENAME = $(SOLUTION_NAME)
ARTIFACTS_BASENAME = $(SOLUTION_NAME)
BUILD_CONFIG = Release
TARGET_NET9 = net9.0
TARGET_NFW481 = net481
SINGLE_SUFFIX = -single
AOT_SUFFIX = -aot
RM = del /F /Q
RMDIR = rmdir /S /Q


all: build

build:
	msbuild /nologo /m /p:Configuration=$(BUILD_CONFIG);Platform="x64" Koturn.Zopfli\libzopfli\libzopfli.vcxproj
	msbuild /nologo /m /p:Configuration=$(BUILD_CONFIG);Platform="x86" Koturn.Zopfli\libzopfli\libzopfli.vcxproj
	dotnet build -c $(BUILD_CONFIG) $(MAIN_PROJECT_FILE)

restore:
	dotnet restore $(SOLUTION_FILE)

deploy: deploy-$(TARGET_NET9)

deploy$(SINGLE_SUFFIX): deploy-$(TARGET_NET9)$(SINGLE_SUFFIX)

deploy$(AOT_SUFFIX): deploy-$(TARGET_NET9)$(AOT_SUFFIX)

deploy-$(TARGET_NET9):
	-dotnet publish -c $(BUILD_CONFIG) -f $(TARGET_NET9) -r win-x64 --no-self-contained \
		-p:PublishDir=..\$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9) \
		-p:PublishTrimmed=false \
		-p:PublishAot=false \
		$(MAIN_PROJECT_FILE)
	xcopy /d /S /Y "$(SOLUTION_NAME)\bin\$(BUILD_CONFIG)\$(TARGET_NET9)\x64\*.dll" "$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)\x64\"
	xcopy /d /S /Y "$(SOLUTION_NAME)\bin\$(BUILD_CONFIG)\$(TARGET_NET9)\x86\*.dll" "$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)\x86\"
	-$(RM) $(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)\*.pdb \
		$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)\*.xml \
		$(ARTIFACTS_BASENAME)-$(TARGET_NET9).zip 2>NUL
	cd $(ARTIFACTS_BASEDIR)
	powershell Compress-Archive -Path $(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9) -DestinationPath ..\$(ARTIFACTS_BASENAME)-$(TARGET_NET9).zip
	cd $(MAKEDIR)

deploy-$(TARGET_NET9)$(SINGLE_SUFFIX):
	-dotnet publish -c $(BUILD_CONFIG) -f $(TARGET_NET9) -r win-x64 --self-contained \
		-p:PublishDir=..\$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(SINGLE_SUFFIX) \
		-p:PublishAot=false \
		-p:PublishSingleFile=true \
		-p:PublishReadyToRun=true \
		$(MAIN_PROJECT_FILE)
	xcopy /d /S /Y "$(SOLUTION_NAME)\bin\$(BUILD_CONFIG)\$(TARGET_NET9)\x64\*.dll" "$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(SINGLE_SUFFIX)\x64\"
	xcopy /d /S /Y "$(SOLUTION_NAME)\bin\$(BUILD_CONFIG)\$(TARGET_NET9)\x86\*.dll" "$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(SINGLE_SUFFIX)\x86\"
	-$(RM) $(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(SINGLE_SUFFIX)\*.pdb \
		$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(SINGLE_SUFFIX)\*.xml \
		$(ARTIFACTS_BASENAME)-$(TARGET_NET9)$(SINGLE_SUFFIX).zip 2>NUL
	cd $(ARTIFACTS_BASEDIR)
	powershell Compress-Archive -Path $(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(SINGLE_SUFFIX) -DestinationPath ..\$(ARTIFACTS_BASENAME)-$(TARGET_NET9)$(SINGLE_SUFFIX).zip
	cd $(MAKEDIR)

deploy-$(TARGET_NET9)$(AOT_SUFFIX):
	-dotnet publish -c $(BUILD_CONFIG) -f $(TARGET_NET9) -r win-x64 --self-contained \
		-p:PublishDir=..\$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(AOT_SUFFIX) \
		$(MAIN_PROJECT_FILE)
	xcopy /d /S /Y "$(SOLUTION_NAME)\bin\$(BUILD_CONFIG)\$(TARGET_NET9)\x64\*.dll" "$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(AOT_SUFFIX)\x64\"
	xcopy /d /S /Y "$(SOLUTION_NAME)\bin\$(BUILD_CONFIG)\$(TARGET_NET9)\x86\*.dll" "$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(AOT_SUFFIX)\x86\"
	-$(RM) $(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(AOT_SUFFIX)\*.pdb \
		$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(AOT_SUFFIX)\*.xml \
		$(ARTIFACTS_BASENAME)-$(TARGET_NET9)$(AOT_SUFFIX).zip 2>NUL
	cd $(ARTIFACTS_BASEDIR)
	powershell Compress-Archive -Path $(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NET9)$(AOT_SUFFIX) -DestinationPath ..\$(ARTIFACTS_BASENAME)-$(TARGET_NET9)$(AOT_SUFFIX).zip
	cd $(MAKEDIR)

deploy-$(TARGET_NFW481):
	-dotnet publish -c $(BUILD_CONFIG) -f $(TARGET_NFW481) --no-self-contained \
		-p:PublishDir=..\$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NFW481) \
		-p:PublishTrimmed=false \
		-p:PublishAot=false \
		$(MAIN_PROJECT_FILE)
	xcopy /d /S /Y "$(SOLUTION_NAME)\bin\$(BUILD_CONFIG)\$(TARGET_NFW481)\x64\*.dll" "$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NFW481)\x64\"
	xcopy /d /S /Y "$(SOLUTION_NAME)\bin\$(BUILD_CONFIG)\$(TARGET_NFW481)\x86\*.dll" "$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NFW481)\x86\"
	-$(RM) $(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NFW481)\*.pdb \
		$(ARTIFACTS_BASEDIR)\$(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NFW481)\*.xml \
		$(ARTIFACTS_BASENAME)-$(TARGET_NFW481).zip 2>NUL
	cd $(ARTIFACTS_BASEDIR)
	powershell Compress-Archive -Path $(ARTIFACTS_SUBDIR_BASENAME)-$(TARGET_NFW481) -DestinationPath ..\$(ARTIFACTS_BASENAME)-$(TARGET_NFW481).zip
	cd $(MAKEDIR)

clean:
	-for %%d in ( $(PROJECT_DIRS) ) do @( \
		@$(RMDIR) %%d\bin %%d\obj 2>NUL \
	)
	-for %%d in ( $(CXX_PROJECT_DIRS) ) do @( \
		@$(RMDIR) %%d\x86 %%d\x64 2>NUL \
	)

distclean: clean
	-$(RMDIR) $(ARTIFACTS_BASEDIR) 2>NUL
	-$(RM) $(ARTIFACTS_BASENAME)-*.zip 2>NUL
